# Blockchain & Applications Project 2: Beatchain
# Cody Gilbert

OrdererOrgs:
  - Name: BeatchainOrg
    Domain: beatchain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: AppDevOrg
    Domain: appdevorg.beatchain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: CreatorOrg
    Domain: creatororg.beatchain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: CustomerOrg
    Domain: customerorg.beatchain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
