# Blockchain & Applications Project 2: Beatchain
# Cody Gilbert

version: '2'

services:

  orderer.beatchain.com:
    container_name: orderer.beatchain.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=BeatchainMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/chaincode/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/beatchain.com/orderers/orderer.beatchain.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/beatchain.com/orderers/orderer.beatchain.com/tls/:/var/hyperledger/orderer/tls
    - orderer.beatchain.com:/var/hyperledger/production/orderer
    - $GOPATH/chaincode/github.com/:/opt/gopath/chaincode/github.com
    ports:
      - 7050:7050

  peer0.appdevorg.beatchain.com:
    container_name: peer0.appdevorg.beatchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.appdevorg.beatchain.com
      - CORE_PEER_ADDRESS=peer0.appdevorg.beatchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.appdevorg.beatchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.appdevorg.beatchain.com:7051
      - CORE_PEER_LOCALMSPID=AppDevMSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/chaincode/github.com/:/opt/gopath/chaincode/github.com
        - ./crypto-config/peerOrganizations/appdevorg.beatchain.com/peers/peer0.appdevorg.beatchain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/appdevorg.beatchain.com/peers/peer0.appdevorg.beatchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.appdevorg.beatchain.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060

  peer0.creatororg.beatchain.com:
    container_name: peer0.creatororg.beatchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.creatororg.beatchain.com
      - CORE_PEER_ADDRESS=peer0.creatororg.beatchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.creatororg.beatchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.creatororg.beatchain.com:7051
      - CORE_PEER_LOCALMSPID=CreatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/chaincode/github.com/:/opt/gopath/chaincode/github.com
        - ./crypto-config/peerOrganizations/creatororg.beatchain.com/peers/peer0.creatororg.beatchain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/creatororg.beatchain.com/peers/peer0.creatororg.beatchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.creatororg.beatchain.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060

  peer0.customerorg.beatchain.com:
    container_name: peer0.customerorg.beatchain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.customerorg.beatchain.com
      - CORE_PEER_ADDRESS=peer0.customerorg.beatchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customerorg.beatchain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customerorg.beatchain.com:7051
      - CORE_PEER_LOCALMSPID=CustomerMSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/chaincode/github.com/:/opt/gopath/chaincode/github.com
        - ./crypto-config/peerOrganizations/customerorg.beatchain.com/peers/peer0.customerorg.beatchain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/customerorg.beatchain.com/peers/peer0.customerorg.beatchain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.customerorg.beatchain.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
      - 9055:6060
